[package]
name = "barrel-derive"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "^0.12", features = ["extra-traits"] }
quote = "^0.4"